### ISSUE TITLE
Reorganize `sendto' subsystem [migrated from ircd-micro issues]

### ISSUE THREAD

**Issue by sariyamelody** [atheme-legacy/tethys#13]
### `u_sendto_chan_pfx`

Something like this would be nice:

``` C
u_sendto_chan_pfx(chan, conn, ST_ALL, CU_PFX_VOICE,
        ":%H PRIVMSG +%C :%s", src, tgt, text);
```

It would also be useful in this situation:

``` C
u_sendto_chan_pfx(c, NULL, ST_USERS, CU_PFX_OP
        ":%H MODE %C %s%s", u, c, m.op.buf, m.op.data);
```

i.e., issue #4 
### Control send based on client CAPs present, client CAPs missing

This is essential for proper implementation of away-notify, account-notify, extended-join, etc., i.e. issue #8

**Comment by sariyamelody** [comment]
@aji wrote two comments on this issue (https://github.com/aji/ircd-micro/issues/26), so I will replicate them in full below.

**Comment by sariyamelody** [comment]
@aji commented

My thought on this is a function called `u_sendto` that has lots of parameters, and a few macros called `u_sendto_chan`, `u_sendto_chan_pfx`, `u_sendto_chan_cap`, etc. that are thin wrappers around `u_sendto`, filling all unneeded fields with default values.

The key is to reduce clutter in message routing code so the exact intention is clear.

**Comment by sariyamelody** [comment]
@aji commented

I sat down and enumerated the different target globbing types, i.e. cases where plain `u_conn_f` cannot be used. I came up with the following functionalities:
- `u_sendto_chan` — Send to local, remote, or local and remote users in a channel, optionally excluding a particular connection.
- `u_sendto_chan_pfx` — Send to local users with a certain status on the channel, optionally excluding a particular connection.
- `u_sendto_chan_flags` — Send to local users in a channel with or without certain flags, optionally excluding etc.
- `u_sendto_visible` — Send to local, remote, or local and remote users visible to a certain user, with or without certain flags, optexconn.
- `u_roster_f` — Send to a roster (covers WALLOPS, snotices, s2s broadcast messages, etc.) optexconn.

These seem to provide a solid base that should cover all immediate requirements of the sendto subsystem.

_Aside_: I am still on the fence about adding another sendto function that sends to local users on a channel, and to all servers. This is right now useful in the case of TOPIC, PART, KICK, and perhaps others where all servers and only the local users in a given channel must be notified of a change in state. With modifications to vsnf that allow arguments to be omitted on a per-connection type basis, this could also be expanded to (T)MODE and JOIN. An equivalent function expanding upon `u_sendto_visible` could be useful for propagating KILL and QUIT. Of course, this can be carried to an extreme, where a new sendto function is created to accommodate every single possible propagation, culminating in a function called `sendto_channel_local_with_capability_butone`, so it's important to recognize where the stopping point is.

**Comment by aji** [comment]
Oh yeah, this one.

What I eventually decided on was a set of macros that work similarly to `MOWGLI_LIST_FOREACH` and `MOWGLI_PATRICIA_FOREACH` called `U_SENDTO_CHAN`, `U_SENDTO_SERVERS`, `U_SENDTO_CHAN_LOCAL`, `U_SENDTO_VISIBLE`, etc. that iterate over unique connections matching the specified criteria. Users can then provide additional matching criteria as needed.
