### ISSUE TITLE
Usermode to hide channel line in /whois

### ISSUE THREAD

**Issue by HelixSpiral** [atheme-legacy/tethys#45]
This could either:
- Hide the whole line (Like +I does on InspIRCd)
- Hide only channels the user doesn't share with the person whoising them (Like +p on UnrealIRCd)

**Comment by ghost** [comment]
What about just doing what freenode's ircd-seven does and use usermode +i (in unrealircd it would be +p), without having to create an entirely new usermode. Maybe even have an option to enable/disable it inside the config.

**Comment by HelixSpiral** [comment]
If we use usermode +i I'd prefer it not have a config option to toggle it. It should either be on or off permanently.

**Comment by aji** [comment]
I like KindOne's idea of a config option to toggle it. But obviously, beacuse of remote WHOIS, the point is defeated if there is a single node on the network that does not have this option enabled.

**Comment by HelixSpiral** [comment]
The reason I don't want to see a config toggle for it is because users should be able to join a network, see which ircd is running, and know which modes do what.

If it has a config toggle some networks running tethys could have +i do one thing, while others would have +i not do it.

If it was an entirely new mode then users could easily determine if a network supports it or not by trying to add the mode, if the mode doesn't exist then the network obviously doesn't support that.

**Comment by ghost** [comment]
The obvious solution would be to add a CAP (labeled modes is on the docket
for IRCv3.3, I believe) which allows clients to be sent a letter<->label
mapping or somesuch.
